package keylog_test

import (
	"encoding/hex"
	"math/rand/v2"
	"os"
	"strings"
	"testing"

	"golang.org/x/mod/sumdb/tlog"

	"github.com/itsalmirr/keystone/keylog"
)

// TestVectors checks LeafHash and ChainHash against
// testdata/vectors.txt, which was generated by an independent Python
// implementation of ADR-001/ADR-002 — never by this package. Each
// vector is also checked against tlog.RecordHash.
func TestVectors(t *testing.T) {
	raw, err := os.ReadFile("testdata/vectors.txt")
	if err != nil {
		t.Fatal(err)
	}
	var prev tlog.Hash
	n := 0
	for _, line := range strings.Split(strings.TrimSpace(string(raw)), "\n") {
		if strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Split(line, ",")
		if len(parts) != 3 {
			t.Fatalf("malformed vector line %q", line)
		}
		data, err := hex.DecodeString(parts[0])
		if err != nil {
			t.Fatal(err)
		}
		leaf := keylog.LeafHash(data)
		if got := hex.EncodeToString(leaf[:]); got != parts[1] {
			t.Errorf("LeafHash(%q) = %s, want %s", parts[0], got, parts[1])
		}
		if oracle := tlog.RecordHash(data); leaf != oracle {
			t.Errorf("LeafHash(%q) != tlog.RecordHash", parts[0])
		}
		prev = keylog.ChainHash(prev, data)
		if got := hex.EncodeToString(prev[:]); got != parts[2] {
			t.Errorf("ChainHash at %q = %s, want %s", parts[0], got, parts[2])
		}
		n++
	}
	if n == 0 {
		t.Fatal("no vectors parsed")
	}
}

// TestLeafHashMatchesTlogRandom is the oracle property test: LeafHash
// must agree with tlog.RecordHash over deterministic pseudo-random
// inputs on every `go test` run. (No fuzz target here on purpose —
// LeafHash is a branchless pure function; fuzz time belongs to the
// decoder, and the vectors above already pin the RFC 6962 values.)
func TestLeafHashMatchesTlogRandom(t *testing.T) {
	rng := rand.NewChaCha8([32]byte{'k', 'e', 'y', 's', 't', 'o', 'n', 'e'})
	buf := make([]byte, 4096)
	for i := 0; i < 512; i++ {
		data := buf[:rng.Uint64()%uint64(len(buf))]
		for j := range data {
			data[j] = byte(rng.Uint64())
		}
		if keylog.LeafHash(data) != tlog.RecordHash(data) {
			t.Fatalf("LeafHash diverges from tlog.RecordHash on %d-byte input %x", len(data), data)
		}
	}
}
